---
name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3

      - name: "Merge"
        uses: fastify/github-action-merge-dependabot@v3.2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor